### ISSUE TITLE
Scanner().scanFile returns `(8, None)`

### ISSUE THREAD

**Issue by tomhamiltonstubber** [clamwin/python-clamav#1]
Hi folks,

Not sure if this is maintained any more but thought I'd give it a go. This is probably an issue due to the fact this project hasn't been worked on since 2018 but if you can shed some light I'd be grateful.

Calling `Scanner().scanFile(b'eicar.txt')` returns `(8, None)`

This happens when scanning both an EICAR file and a clean one.

In the meantime, I'm going to dig around myself.

**Comment by sherpya** [comment]
8 is an error, `CL_EOPEN` (Can't open directory), I've made some changes, now a result that is not 0 or 1 will raise ClamvException
